# Generated by Django 5.0.3 on 2024-03-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_usercontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorContact',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200, primary_key=True, serialize=False)),
                ('contact', models.CharField(max_length=12, unique=True)),
                ('message', models.TextField()),
            ],
        ),
    ]
