# Generated by Django 5.0.3 on 2024-03-16 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_doctorcontacts_delete_doctorcontact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DoctorContacts',
            new_name='DoctorsContacts',
        ),
    ]
