# Generated by Django 5.0.3 on 2024-03-16 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_doctorcontacts_doctorscontacts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DoctorsContacts',
            new_name='DoctorsMessage',
        ),
    ]
