# Generated by Django 5.0.3 on 2024-03-16 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_doctorscontacts_doctorsmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorsMessage',
        ),
    ]
