# Generated by Django 5.0.3 on 2024-03-17 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_doctorsmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorDetail',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200, primary_key=True, serialize=False)),
                ('contact', models.CharField(max_length=12, unique=True)),
                ('experience', models.CharField(max_length=100)),
                ('clinicname', models.TextField()),
                ('city', models.CharField(max_length=200)),
                ('consultationfee', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
