# Generated by Django 5.0.3 on 2024-03-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_bookappointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookappointment',
            name='appdate',
            field=models.CharField(max_length=200),
        ),
    ]
