# Generated by Django 5.0.3 on 2024-03-22 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_bookappointment_appdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bookappointment',
        ),
    ]
